adapt: shell.c value_function_loop.c ucont.c amoeba.c amotry.c err_kakp.c rtbis.c nelder.c golden.c  err_hrahrp.c  solveModel.c sim_peeps.c save_results.c cond_v.c  amoeba_r.c amotry_r.c  err_lb.c  splie2.c spline.c splint.c splin2.c amoeba_nr.c amotry_nr.c nelder_nr.c 
	gcc -fopenmp -o adapt shell.c value_function_loop.c ucont.c amoeba.c amotry.c  err_kakp.c rtbis.c nelder.c  golden.c  err_hrahrp.c  solveModel.c sim_peeps.c save_results.c  amoeba_r.c amotry_r.c  err_lb.c  splie2.c spline.c splint.c splin2.c amoeba_nr.c amotry_nr.c nelder_nr.c cond_v.c -lm 

